--- #YAML:1.0
name:               POE-Component-IRC-Plugin-Logger-Irssi
version:            0.001001
abstract:           Log IRC events like irssi
author:
    - Marius Gavrilescu <marius@ieval.ro>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.014000
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     0
